import testMethods as t
def test_regtests():
    driver = t.setWDInstanse()
    maildriver = t.setMailDriver()
    mailurl = t.setMailUrl()
    regurl = t.setTestURL()
    t.getRegURL(regurl, driver)
    t.getMailURL(mailurl, maildriver)
    email = t.getEmail(maildriver)
    t.typeEmail(driver, email)
    t.typeFirst(driver, t.randomStr())
    t.typeLast(driver, t.randomStr())
    t.selectCity(driver)
    t.selectExperience(driver)
    pw = t.getPassword()
    t.typePassword(driver, pw)
    t.writeCredentials(email, pw)
    t.clickJoin(driver)
    t.verifyEmail(maildriver)
    t.login(driver, email, pw)
    t.chooseGender(driver)
    t.setAge(driver)
    t.selectMonth(driver)
    t.selectEXP(driver)
    t.userTips(driver)